using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HomeMyDay.Models
{
	/// <summary>
	/// Base model for EF classes
	/// </summary>
	public class BaseModel
	{
		/// <summary>
		/// The ID of the model. Automatically generated by the database.
		/// </summary>
		[Key]
		public long Id { get; set; }
	}
}
