using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HomeMyDay.Models
{
    public class Country
    {
		/// <summary>
		/// The ID of the country. Generated by the database.
		/// </summary>
		[Key]
		public int Id { get; set; }

		/// <summary>
		/// The continent that this country is located in.
		/// </summary>
		public string Continent { get; set; }

		/// <summary>
		/// The name of this country.
		/// </summary>
		public string Name { get; set; }
    }
}
