// <auto-generated />
using HomeMyDay.Core.Models;
using HomeMyDay.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HomeMyDay.Infrastructure.Migrations
{
    [DbContext(typeof(HomeMyDayDbContext))]
    partial class HolidayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeMyDay.Core.Models.Booking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DepartureDate");

                    b.Property<bool>("InsuranceCancellationAllRisk");

                    b.Property<bool>("InsuranceCancellationBasic");

                    b.Property<bool>("InsuranceExplore");

                    b.Property<bool>("InsuranceService");

                    b.Property<int>("InsuranceType");

                    b.Property<DateTime>("ReturnDate");

                    b.Property<bool>("TransferFromAirport");

                    b.Property<bool>("TransferToAirport");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.BookingPerson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Baggage");

                    b.Property<DateTime?>("BirthDate")
                        .IsRequired();

                    b.Property<long?>("BookingId");

                    b.Property<bool>("BookingOwner");

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<long>("CountryId");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<int?>("HouseNumber")
                        .IsRequired();

                    b.Property<string>("HouseNumberSuffix");

                    b.Property<string>("Initials")
                        .IsRequired();

                    b.Property<string>("Insertion");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<long>("NationalityId");

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<string>("PostalCode")
                        .IsRequired();

                    b.Property<string>("Salutation")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CountryId");

                    b.HasIndex("NationalityId");

                    b.ToTable("BookingPerson");
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryCode");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.DateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.HasKey("Id");

                    b.ToTable("DateEntity");
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.FaqCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.HasKey("Id");

                    b.ToTable("FaqCategory");
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.FaqQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<long?>("CategoryId");

                    b.Property<string>("Question");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FaqQuestions");
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.MediaObject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("Primary");

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("MediaObjects");
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.Newspaper", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Email")
                        .HasName("Alt_Email");

                    b.ToTable("Newspapers");
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.Page", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Page_Name");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Page");
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Approved");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Name");

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.Vacancy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AboutFunction");

                    b.Property<string>("AboutVacancy");

                    b.Property<string>("City");

                    b.Property<string>("Company");

                    b.Property<string>("JobRequirements");

                    b.Property<string>("JobTitle");

                    b.Property<string>("WeOffer");

                    b.HasKey("Id");

                    b.ToTable("Vacancies");
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.BookingPerson", b =>
                {
                    b.HasOne("HomeMyDay.Core.Models.Booking")
                        .WithMany("Persons")
                        .HasForeignKey("BookingId");

                    b.HasOne("HomeMyDay.Core.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HomeMyDay.Core.Models.Country", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HomeMyDay.Core.Models.FaqQuestion", b =>
                {
                    b.HasOne("HomeMyDay.Core.Models.FaqCategory", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
